
server:
  port: 9090

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/jwttest?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

mybatis:
  # mapper ?? ??
  mapper-locations: mapper/**/*.xml
  type-aliases-package: com.jwt.tutorial.model
  configuration:
    map-underscore-to-camel-case: true


#  jpa:
#    open-in-view: false
#    hibernate:
#      ddl-auto: update
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      use-new-id-generator-mappings: false
#    show-sql: true
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true

    logging:
      level:
        org.hibernate.SQL: debug
        jdbc.sqlonly: debug
        org.hibernate.type: trace
        org.springframework.boot.autoconfigure: ERROR
